[package]
name = "xybrid-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true
name = "xybrid_macros"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

